- hosts: localhost 
  become: yes
  tasks: 
  - name: install apt packages 
    apt: name={{item}} state=latest
    with_items:
      - git
      - gitk
      - vim
      - arandr
      - curl
      - httpie
      - rsync
      - chromium-browser
      - apt-transport-https
      - ca-certificates
      - git-cola
      - curl
      - software-properties-common
      - docker-compose

        # add nvidia ppa
        # install nvidia-390

  - name:    Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name:    Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} test 

  - name:    Install Docker
    apt:     name=docker-ce

  - name: Ensure group "docker" exists
    group:
      name: docker 
      state: present

   # ATTENTION: this task can potentially create new users!
  - name: Add users to the docker group
    user:
      name: haakon
      groups: docker
      append: yes
    with_items: docker_group_members
    tags: docker
    notify: you need to restart to setup docker group for your user


  - name: install key (apt)
    become: yes
    apt_key:
      url: 'https://packages.microsoft.com/keys/microsoft.asc'
      state: present
  
  - name: install VS Code repo (apt)
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present
  
  - name: install VS Code (apt)
    become: yes
    apt:
      name: code
      state: present

  - name: install chrome apt key
    become: yes
    apt_key:
      url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
      state: present

  - name: install chrome repo
    become: yes
    apt_repository:
      update_cache: yes
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      state: present

  - name: install google chrome
    become: yes
    apt:
      name: google-chrome-stable

  - name: Adds gcloud key
    become: yes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adds gcloud repos
    become: yes
    apt_repository:
      repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
      update_cache: yes


  - name: Installs google-cloud-sdk
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - google-cloud-sdk
      - python-pip
      - python-setuptools
      - python-openssl

  - name: Install kubectl
    command: snap install kubectl --classic

    # not sure if this works..
  - name: Setup kubectl shell autocompletion
    command: echo "source <(kubectl completion bash)" >> /home/haakon/.bashrc

  - name: copy gitignore
    copy:
      src: files/.gitconfig
      dest: /home/haakon/


    # not sure if this works..
  - name: setup PS1 with git branch info
    command: echo "$(cat files/ps1)" >> /home/haakon/.bashrc

  - name: increase inofity  watch limit
    command: echo "fs.inotify.max_user_watches = 524288" | sudo tee --append /etc/sysctl.conf

    #TODO: install nodejs/npm
